### PR TITLE
Create clock.tsx and update Header.tsx and main.css

### PR DESCRIPTION
**Pull request by shivam0211**

### CODE REVIEW

**Review by Jigar3 — CHANGES_REQUESTED** [review]
You have installed the react-live-clock package. This would have updated the package.json file as well. Add package.json as well while commiting

**Comment by shivam0211** [comment]
Does it need any more changes?

**Review by Jigar3 — CHANGES_REQUESTED** [review]
Maybe you could add the seconds in the clock as well. And upload a screenshot of the same. You uploaded package-lock.json and not package.json

**Comment by shivam0211** [comment]
screenshot 2019-01-16 at 11 43 13 pm

**Comment by Jigar3** [comment]
@shivam0211 Good job. One last thing, squash all the 7 commits into a single commit

**Comment by Jigar3** [comment]
@shivam0211 squash the 7 commits into a single commit.

**Pull request merged**
