### PR TITLE
Update read.me (issue #4)

### PR DESCRIPTION
**Pull request by Archies11**
I have updated the text in the file but I am not able to understand how can I access this application on the web so that I may add some screenshots of the application as well.
Working link: https://archies11.github.io/Wall-Street/

### CODE REVIEW

**Comment by Jigar3** [comment]
@Archies11 Good job.

**Comment by Archies11** [comment]
I have added a screenshot of the website also.Should i file another pull request for the same?

**Comment by Jigar3** [comment]
Show me the live link.

**Comment by Archies11** [comment]
Live Link: https://archies11.github.io/Wall-Street/

**Comment by Jigar3** [comment]
The link doesn't contain any screenshot

**Pull request merged**
